name = "ts-worker"
type = "javascript"
zone_id = ""
account_id = "110baefd8601421d8e398ee2354348bc"
route = ""
workers_dev = true
compatibility_date = "2022-04-04"
kv_namespaces = [ 
  { binding = "DATATEST", preview_id = "641907a233934469867878c2572f8889", id = "641907a233934469867878c2572f8889" }
]

[dev]
port = 9000

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"


[triggers]
crons = ["*/1 * * * *"]